@startuml

class User {
    int id
    string name
    string login
    string password
}

class Transactions {
    int id
    int user_id
    string description
    int amount
    datetime date
}

User "1" -- "many" Transactions

@enduml